export enum ConfigKey {
  PORT = "PORT",
  NODE_ENV = "NODE_ENV",
  SDK_FINANCE_BASE_URL = "SDK_FINANCE_BASE_URL",
  INTERNAL_AUTH_SECRET_BANKING_SERVICE = "INTERNAL_AUTH_SECRET_BANKING_SERVICE",
  LOG_LEVEL = "LOG_LEVEL",
  LOG_TO_CONSOLE = "LOG_TO_CONSOLE",
  LOG_TO_FILE = "LOG_TO_FILE",
  LOG_FILE_PATH = "LOG_FILE_PATH",
  REDIS_HOST = "REDIS_HOST",
  REDIS_PORT = "REDIS_PORT",
}
